version: '3.9'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/dev.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: fastapi_example_cases_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/fastapi_example_cases_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    env_file:
      - ./.dev_db.env

